---
# tasks file for mediawiki
- name: Pre-requiste pkgs list for installing Mediawiki
  yum:
   name: "{{item}}"
   state: present
  loop:
   - "{{pkg}}"
- name: Start the mysqldb service
  service:
   name: mariadb
   state: started
- name: MySql Secure Installation Steps
  shell: echo -e "\n\nredhat\nredhat\ny\ny\ny\ny\ny " | mysql_secure_installation 2>/dev/null
- name: Mysql Commands
  copy:
   src: dump/
   dest: /tmp
- name: DB user and password pass
  copy:
   src: mycnf/
   dest: ~/
   mode: '0600'
- name: DB Creation
  mysql_db:
   name: wikidatabase
   state: import
   target: /tmp/dump.sql.bz2
- name: Enable the mariadb service
  systemd:
   name: mariadb
   enabled: yes
- name: Enable the httpd service
  systemd:
   name: httpd
   enabled: yes
- name: Create a sample user
  user:
   name: mediawiki
   state: present
- name: Download Mediawiki tar
  get_url:
   url: "{{mediaurl}}"
   dest: "{{mediahome}}"
- name: Untar the Mediawiki
  shell: cd /var/www;tar -zxf "{{mediahome}}"/mediawiki-1.34.2.tar.gz;ln -s mediawiki-1.34.2/ mediawiki
- name: Replace Document Root
  lineinfile:
   path: "{{httpdconfpath}}"
   regexp: 'DocumentRoot "/var/www/html"'
   line: 'DocumentRoot "/var/www"'
- name: Replace Directory Index
  lineinfile: 
   path: "{{httpdconfpath}}"
   regexp: 'DirectoryIndex index.html'
   line: 'DirectoryIndex index.html index.html.var index.php'
- name: Ownership tweak
  shell: chown -R apache:apache /var/www/mediawiki-1.34.2
  notify:
   - httpstart
- name: Firewall ports open http
  firewalld:
   service: "{{ firewall_service1 }}"
   permanent: true
   state: enabled
   immediate: true
- name: Firewall ports open https
  firewalld:
   service: "{{ firewall_service2 }}"
   permanent: true
   state: enabled
   immediate: true
- name: Context tweak to staisfy selinux policy
  shell: restorecon -FR /var/www/mediawiki-1.34.2/;restorecon -FR /var/www/mediawiki
- name: Downloading the PHP7 related Remi Repo
  get_url:
   url: "{{remiurl}}"
   dest: /root
- name: Update the remi repo
  shell: rpm -Uvh /root/remi-release-7.rpm
  register: output
  ignore_errors: yes
- debug:
   var: output
- name: Enable the remi repo  
  shell: yum-config-manager --enable remi-php73
- name: Updating the packages
  yum:
   name: "*"
   state: latest
  notify:
   - httpstart
